### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ChrisMacNaughton**
Add some good content

### CODE REVIEW

**Comment by SEKCobra** [comment]
I feel like this project has been abandoned before it really started. A real disappointment. It had so much potential at becoming the one and only homework.

**Comment by Banandana** [comment]
What's the licensing on the code? I really want to use this for my own homework, but don't want to infringe on any copyrights.

**Comment by SEKCobra** [comment]
There is no licensing when there's no LICENSE file included, so I am just going to make this my work now. Everyone who forks it owes me 5 $ service charge.

**Comment by Banandana** [comment]
ur paypal has been successfully charged

**Pull request closed without merging**
