### PR TITLE
Added name!

### PR DESCRIPTION
**Pull request by backwardspy**

### CODE REVIEW

**Comment by benjojo** [comment]
Can you please write some unit tests for this change set please before it can be merged into the official repo

**Comment by backwardspy** [comment]
Yessir. I'm going to make a UML diagram for it as well.

**Comment by Banandana** [comment]
Make sure it uses standard styles, readability is very important as well.

**Comment by backwardspy** [comment]
What do you take me for, some kind of style-crazy heathen!?

**Comment by Banandana** [comment]
I don't think you'll get knocked down for it this time, but next time, please include more info when you do pull requests such as this. It's very important in a repository based system such as this.

**Pull request closed without merging**
